#!/usr/bin/env python3
"""Lightweight HTTP server for the GMD audit dashboard.

Serves index.html + data.json on http://127.0.0.1:8765.
Accepts POST /comment to persist comments to comments.json (atomic write)
AND appends every save to comments.log (append-only safety net).

Run:
    python serve.py [port]

Stop with Ctrl+C.
"""
from __future__ import annotations
import datetime as _dt
import hashlib
import http.server
import json
import os
import shutil
import socketserver
import subprocess
import sys
import tempfile
import threading
from pathlib import Path
from urllib.parse import urlparse, parse_qs

ROOT = Path(__file__).resolve().parent
INDEX_PATH = ROOT / "index.html"
DATA_PATH = ROOT / "data.json"
COMMENTS_PATH = ROOT / "comments.json"
LOG_PATH = ROOT / "comments.log"
BACKUP_DIR = ROOT / "backups"
BUILD_AUDIT_LOG = ROOT / "build_audit_log.py"
FLAGS_PATH = ROOT / "flags.parquet"
REVIEWER_PATH = ROOT / "reviewer.json"
DIAGNOSE_PY = ROOT / "diagnose.py"
FINDINGS_PATH = ROOT / "findings.json"          # feed for the "Findings" tab (diagnose.py --json)
REPO = ROOT.parent
FLAGS_PY = ROOT / "flags.py"
BUILD_DATA_PY = ROOT / "build_data.py"
MANIFEST_PATH = ROOT / "flags_manifest.json"    # input fingerprints, written by flags.py

# Background "Regenerate flags" job (flags.py is tens-of-seconds slow, so it
# runs off the request thread). ThreadingTCPServer handles each request in its
# own thread; this dict + lock track the single in-flight regen.
_REGEN_LOCK = threading.Lock()
_REGEN_STATE: dict = {
    "status": "idle",      # idle | running | done | error
    "kind": None,          # regen (full) | resuppress (fast)
    "started_at": None,
    "finished_at": None,
    "step": None,          # which subprocess is/was running
    "error": None,
    "log_tail": None,
    "returncode": None,
}

# Lazy-loaded vetting ledger (audit_dashboard/ledger.py); fall back to None
# if the module fails to import so the server still serves data.json.
import importlib.util as _imp
_ledger_spec = _imp.spec_from_file_location("_ledger", ROOT / "ledger.py")
if _ledger_spec and _ledger_spec.loader:
    try:
        ledger = _imp.module_from_spec(_ledger_spec)
        _ledger_spec.loader.exec_module(ledger)
    except Exception as _e:
        print(f"[warn] ledger import failed: {_e}", file=sys.stderr)
        ledger = None
else:
    ledger = None
# Embedded mode (default ON for this data-review copy): disable everything that
# reaches OUTSIDE data-review/ -- no git commit/push, no docs/*.md rebuilds, no heavy
# rebuild subprocesses. The browser-facing embed must never mutate the host repo.
# Set DATA_REVIEW_EMBED=0 to restore the original standalone behavior.
EMBED_MODE = os.environ.get("DATA_REVIEW_EMBED", "1") != "0"

# When True, regenerate docs/GMD_AUDIT_LOG.md after every successful save. Off in
# embedded mode (those docs live in the grandfathered GMD repo, not here).
AUTO_REBUILD_AUDIT_LOG = not EMBED_MODE

if not COMMENTS_PATH.exists():
    COMMENTS_PATH.write_text("{}")
BACKUP_DIR.mkdir(exist_ok=True)


def atomic_write_text(path: Path, content: str) -> None:
    """Write `content` to `path` atomically: temp file + rename."""
    fd, tmp = tempfile.mkstemp(dir=str(path.parent), prefix=".tmp.", suffix=".json")
    try:
        with os.fdopen(fd, "w") as f:
            f.write(content)
        os.replace(tmp, path)
    except Exception:
        try:
            os.unlink(tmp)
        except FileNotFoundError:
            pass
        raise


def append_log(record: dict) -> None:
    """Append one JSONL line to the comments log (no-fsync; OS-buffered ok)."""
    with open(LOG_PATH, "a") as f:
        f.write(json.dumps(record, separators=(",", ":")) + "\n")


import re as _re
_TIMESTAMP_LINE_RE = _re.compile(r"_Auto-generated by `[^`]+` on \*\*[^*]+\*\*\._")


def _has_substantive_diff(rel_path: str, repo: Path) -> bool:
    """Return True iff the working-tree file differs from HEAD in any line
    OTHER than the auto-generated timestamp banner. Without this, every
    rebuild would create a "useless" diff (timestamp moved by 1 sec) and
    sync would always commit + push even when nothing else changed."""
    abs_path = repo / rel_path
    if not abs_path.exists():
        return False
    try:
        head = subprocess.run(
            ["git", "show", f"HEAD:{rel_path}"],
            cwd=str(repo), capture_output=True, text=True,
        )
        if head.returncode != 0:
            # untracked / not in HEAD → genuinely new
            return True
    except Exception:
        return True
    cur = abs_path.read_text()
    return _TIMESTAMP_LINE_RE.sub("", cur) != _TIMESTAMP_LINE_RE.sub("", head.stdout)


def commit_and_push_audit_logs() -> dict:
    """Regenerate the audit log, then `git add` + `git commit` + `git push`
    the markdown files. Used by BOTH the manual `/sync` endpoint and the
    Ctrl+C shutdown handler.

    Returns a dict describing what happened — caller renders to user. Keys:
      ok           — overall success (commit landed, push attempted)
      committed    — bool, did we actually create a commit?
      pushed       — bool, did `git push` succeed?
      message      — human-readable status line
      sha          — committed sha if any
      error        — populated on any failure
    """
    repo = ROOT.parent
    files = [
        # vetting.jsonl is the SOURCE OF TRUTH for review decisions -- commit
        # it first so approvals survive even if the worktree is wiped. The
        # docs/*.md are the regenerated human-readable views.
        "audit_dashboard/vetting.jsonl",
        "docs/GMD_AUDIT_LOG.md",
        "docs/SOURCE_ISSUES.md",
        "docs/AUDIT_CONSOLIDATED.md",
    ]
    # 1) regenerate so the on-disk MDs reflect the very latest comments.json
    try:
        maybe_rebuild_audit_log()
    except Exception as e:
        return {"ok": False, "committed": False, "pushed": False,
                "error": f"rebuild failed: {e}",
                "message": "audit-log rebuild failed — nothing pushed"}
    branch = subprocess.run(["git", "rev-parse", "--abbrev-ref", "HEAD"],
                            cwd=str(repo), capture_output=True, text=True).stdout.strip()
    head_before = subprocess.run(["git", "rev-parse", "HEAD"], cwd=str(repo),
                                 capture_output=True, text=True).stdout.strip()

    # 2) detect whether any of the target files has a SUBSTANTIVE diff vs HEAD
    # (ignoring the auto-generated timestamp line, otherwise every rebuild
    # looks like a real change).
    changed = []
    for rel in files:
        if (repo / rel).exists() and _has_substantive_diff(rel, repo):
            changed.append(rel)
    committed = False
    sha = head_before
    if changed:
        # 3) stage + commit (only the audit-log files; other working-tree
        # changes are deliberately left alone)
        try:
            subprocess.run(["git", "add", "--"] + changed, cwd=str(repo),
                           check=True, capture_output=True, text=True)
            ts = _dt.datetime.now().strftime("%Y-%m-%d %H:%M")
            ncom = "?"
            try:
                ncom = str(len(json.loads(COMMENTS_PATH.read_text() or "{}")))
            except Exception:
                pass
            msg = f"audit: sync GMD_AUDIT_LOG.md ({ncom} reviews, {ts})"
            subprocess.run(["git", "commit", "-m", msg], cwd=str(repo),
                           check=True, capture_output=True, text=True)
            sha = subprocess.run(["git", "rev-parse", "HEAD"], cwd=str(repo),
                                 capture_output=True, text=True).stdout.strip()
            committed = True
        except subprocess.CalledProcessError as e:
            err = (e.stderr or e.stdout or "").strip() if hasattr(e, "stderr") else str(e)
            return {"ok": False, "committed": False, "pushed": False,
                    "error": err, "message": f"commit failed: {err}"}
    else:
        # Quietly revert the timestamp-only diffs so `git status` doesn't nag.
        for rel in files:
            if (repo / rel).exists():
                subprocess.run(["git", "checkout", "HEAD", "--", rel],
                               cwd=str(repo), capture_output=True)

    # 4) integrate the remote (ALWAYS — even with a clean tree). Sync should
    # PULL new code/vetting from GitHub, not just push ours. fetch + rebase
    # replays any local commit on top of origin/branch. On conflict we abort
    # and keep our commit local rather than leaving a half-rebased tree.
    pulled = 0
    pulled_files: list[str] = []
    try:
        fetch = subprocess.run(["git", "fetch", "origin", branch],
                               cwd=str(repo), capture_output=True, text=True, timeout=60)
        if fetch.returncode == 0:
            # commits on origin we don't yet have (relative to pre-commit HEAD)
            rl = subprocess.run(
                ["git", "rev-list", "--count", f"{head_before}..origin/{branch}"],
                cwd=str(repo), capture_output=True, text=True)
            pulled = int(rl.stdout.strip() or "0") if rl.returncode == 0 else 0
            if pulled:
                df = subprocess.run(
                    ["git", "diff", "--name-only", f"{head_before}", f"origin/{branch}"],
                    cwd=str(repo), capture_output=True, text=True)
                pulled_files = [f for f in df.stdout.splitlines() if f.strip()]
            rb = subprocess.run(["git", "rebase", f"origin/{branch}"],
                                cwd=str(repo), capture_output=True, text=True, timeout=60)
            if rb.returncode != 0:
                subprocess.run(["git", "rebase", "--abort"], cwd=str(repo),
                               capture_output=True, text=True)
                err = (rb.stderr or rb.stdout or "").strip()
                tail = f"committed {sha[:10]} locally — " if committed else ""
                return {"ok": False, "committed": committed, "pushed": False,
                        "sha": sha[:10], "error": err,
                        "message": f"{tail}rebase onto origin/{branch} failed "
                                   f"(conflict); resolve manually: {err[:200]}"}
    except Exception as e:
        print(f"[warn] sync fetch/rebase skipped: {e}", file=sys.stderr)

    # 5) push our commit if we made one.
    pushed = False
    push_err = ""
    if committed:
        try:
            push = subprocess.run(["git", "push", "origin", branch], cwd=str(repo),
                                  capture_output=True, text=True, timeout=60)
            pushed = push.returncode == 0
            if not pushed:
                push_err = (push.stderr or push.stdout or "").strip()
        except Exception as e:
            push_err = str(e)

    # 6) if origin brought in code/data (anything beyond our own vetting.jsonl),
    # rebuild the dashboard data so a browser refresh shows it. flags.parquet
    # itself is left to the autoserve supervisor (its recompute is slow).
    code_updated = bool(pulled_files and any(
        f != "audit_dashboard/vetting.jsonl" for f in pulled_files))
    if code_updated:
        try:
            subprocess.run([sys.executable, "audit_dashboard/build_data.py"],
                           cwd=str(repo), capture_output=True, text=True, timeout=600)
        except Exception as e:
            print(f"[warn] data.json rebuild after pull failed: {e}", file=sys.stderr)

    # 7) compose the status line.
    parts = []
    if committed:
        parts.append(f"pushed {sha[:10]}" if pushed else f"committed {sha[:10]} locally")
    if pulled:
        refresh = " — refresh your browser" if code_updated else ""
        parts.append(f"pulled {pulled} new commit(s) from GitHub{refresh}")
    if not parts:
        parts.append("up to date — nothing to push or pull")
    ok = (pushed or not committed) and not push_err
    out = {"ok": ok, "committed": committed, "pushed": pushed,
           "pulled": pulled, "code_updated": code_updated,
           "sha": sha[:10], "message": "; ".join(parts)}
    if push_err:
        out["error"] = push_err
        out["message"] += f" — push failed: {push_err}"
    return out


def final_commit_and_push() -> None:
    """Ctrl+C shutdown wrapper around commit_and_push_audit_logs() — prints
    status to stdout instead of returning JSON."""
    r = commit_and_push_audit_logs()
    print(f"  {r.get('message','(no message)')}")
    if r.get("error") and not r.get("pushed"):
        print(f"       (commit kept locally — run `git push` from "
              f"{ROOT.parent} to retry)")


def maybe_rebuild_audit_log() -> None:
    """Run build_audit_log.py in-process to refresh docs/GMD_AUDIT_LOG.md.

    Best-effort: any error is logged but does not break the save (the actual
    persistence to comments.json + comments.log is already done by the time
    we get here)."""
    if not AUTO_REBUILD_AUDIT_LOG:
        return
    if not BUILD_AUDIT_LOG.exists():
        return
    try:
        # Run as a subprocess so a syntax error in build_audit_log.py never
        # crashes the serve.py interpreter.
        subprocess.run(
            [sys.executable, str(BUILD_AUDIT_LOG)],
            cwd=str(ROOT.parent),
            timeout=20,
            check=False,
            capture_output=True,
        )
    except Exception as e:
        print(f"[warn] audit log rebuild failed: {e}")


def rebuild_findings() -> None:
    """Refresh findings.json via `diagnose.py --json`. Best-effort; run lazily
    when the Findings tab requests /findings so the feed reflects the latest
    pending-fix decisions without slowing down every comment save."""
    if EMBED_MODE or not DIAGNOSE_PY.exists():
        return  # embed: diagnose.py is GMD-coupled (reads data/final, writes docs/); skip
    try:
        subprocess.run(
            [sys.executable, str(DIAGNOSE_PY), "--json"],
            cwd=str(ROOT.parent), timeout=60, check=False, capture_output=True,
        )
    except Exception as e:
        print(f"[warn] findings rebuild failed: {e}")


# Cached flag annotations from flags.parquet. Used by /comment to fan a
# pair-level comment out into one ledger record per flagged cell. Keyed on
# flags.parquet's mtime so a /regen or /resuppress that rewrites the parquet
# (with revised values) invalidates the cache -- otherwise fan-out would stamp
# stale values onto new approvals and value-keyed suppression would re-surface
# the flag the reviewer just cleared.
_FLAG_CACHE: list[dict] | None = None
_FLAG_CACHE_MTIME: int | None = None


def _load_flags_for_fanout() -> list[dict]:
    """Return [{iso3, year, variable, source, reason_type, value}, ...] for
    every flagged cell currently in flags.parquet. Cached, keyed on mtime."""
    global _FLAG_CACHE, _FLAG_CACHE_MTIME
    if not FLAGS_PATH.exists():
        _FLAG_CACHE, _FLAG_CACHE_MTIME = [], None
        return _FLAG_CACHE
    mtime = FLAGS_PATH.stat().st_mtime_ns
    if _FLAG_CACHE is not None and _FLAG_CACHE_MTIME == mtime:
        return _FLAG_CACHE
    try:
        import pandas as pd  # local import; only needed when ledger is used
    except ImportError:
        _FLAG_CACHE, _FLAG_CACHE_MTIME = [], mtime
        return _FLAG_CACHE
    df = pd.read_parquet(FLAGS_PATH)
    reason_cols = [c for c in df.columns if c.startswith("reason_")]
    out: list[dict] = []
    iso = df["ISO3"].astype(str).values
    var = df["variables"].astype(str).values
    yr = df["year"].values
    src = df["source"].astype(str).values
    val = df["value"].values if "value" in df.columns else [float("nan")] * len(df)
    for c in reason_cols:
        col = df[c].values
        short = c.removeprefix("reason_")
        for i in (col == 1.0).nonzero()[0]:
            si = src[i] if src[i] and src[i] != "nan" else None
            yri = None if yr[i] != yr[i] else int(yr[i])  # NaN check
            vi = None if val[i] != val[i] else float(val[i])  # NaN -> None
            out.append({
                "iso3": iso[i], "year": yri, "variable": var[i],
                "source": si, "reason_type": short, "value": vi,
            })
    _FLAG_CACHE = out
    _FLAG_CACHE_MTIME = mtime
    print(f"[serve] cached {len(out)} flag rows for fan-out")
    return _FLAG_CACHE


def _fan_out_comment_to_ledger(key: str, entry: dict) -> int:
    """When the user saves a pair-level comment, fan it out into the
    vetting ledger: one record per currently-flagged cell in the pair.

    Key shape:
      ARG_rGDP           -> pair-level: fan to every flagged cell in (ARG, rGDP)
      ARG_rGDP_Mitchell  -> source-scoped: fan only to cells where source=Mitchell

    Returns the number of ledger records created. 0 if ledger is offline
    or no flagged cells match."""
    if ledger is None:
        return 0
    # Parse the key. ISO3 is 3 letters; the rest is variable [+_source].
    import re
    m = re.match(r"^([A-Z]{3})_(.+)$", key)
    if not m:
        return 0
    iso3, rest = m.group(1), m.group(2)
    # If the trailing token is a known source name in flags.parquet,
    # treat it as source-scoped; otherwise the whole `rest` is variable.
    flag_cells = _load_flags_for_fanout()
    sources_for_pair = {f["source"] for f in flag_cells
                        if f["iso3"] == iso3 and "_" in rest}
    source_scope: str | None = None
    var_for_match = rest
    if "_" in rest:
        # Tentative split: trailing underscore-token might be a source
        cand_var, cand_src = rest.rsplit("_", 1)
        cand_full_sources = {f["source"] for f in flag_cells
                             if f["iso3"] == iso3 and f["variable"] == cand_var}
        if cand_src in cand_full_sources:
            source_scope = cand_src
            var_for_match = cand_var
    # Pull flagged cells for the matched pair (and source if scoped).
    matching = [
        f for f in flag_cells
        if f["iso3"] == iso3 and f["variable"] == var_for_match
        and (source_scope is None or f["source"] == source_scope)
    ]
    if not matching:
        return 0
    # Prefer an explicit disposition; else infer from the approved flag.
    explicit = entry.get("status")
    if explicit in ("vetted-correct", "known-limitation", "pending-fix"):
        status = explicit
    else:
        status = "vetted-correct" if entry.get("approved") else "pending-fix"
    justification = (entry.get("comment") or "").strip() or {
        "vetted-correct": "(blank-approval; no comment supplied)",
        "known-limitation": "(known-limitation; no comment supplied)",
        "pending-fix": "(commented-only)",
    }.get(status, "(commented-only)")
    approved_at = entry.get("ts") or _dt.datetime.now(_dt.timezone.utc).isoformat(timespec="seconds")
    n = 0
    import uuid
    session_id = uuid.uuid4().hex[:12]
    reviewer = get_reviewer() or "dashboard"
    for cell in matching:
        body = {
            "iso3": cell["iso3"],
            "year": cell["year"],
            "variable": cell["variable"],
            "source": cell["source"],
            "reason_type": cell["reason_type"],
            "value": cell.get("value"),
            "status": status,
            "justification": justification,
            "approved_by": reviewer,
            "approved_at": approved_at,
            "refs": [{"session": session_id, "comment_key": key}],
        }
        try:
            ledger.append("vet", body, by_user=reviewer)
            n += 1
        except Exception as e:
            print(f"[warn] ledger fan-out failed for {body!r}: {e}", file=sys.stderr)
    return n


def get_reviewer() -> str:
    """Current reviewer handle, or '' if unset. Stored in reviewer.json
    (gitignored). Falls back to git config user.email on first read."""
    try:
        if REVIEWER_PATH.exists():
            return str(json.loads(REVIEWER_PATH.read_text()).get("reviewer", "")).strip()
    except Exception:
        pass
    # Seed from git once.
    try:
        email = subprocess.run(["git", "config", "user.email"], cwd=str(ROOT.parent),
                               capture_output=True, text=True, timeout=5).stdout.strip()
        if email:
            set_reviewer(email)
            return email
    except Exception:
        pass
    return ""


def set_reviewer(handle: str) -> None:
    handle = (handle or "").strip()
    atomic_write_text(REVIEWER_PATH, json.dumps({"reviewer": handle}))


def reviewed_this_week(reviewer: str) -> int:
    """Count active vetting records approved by `reviewer` in the last 7 days."""
    if ledger is None or not reviewer:
        return 0
    try:
        import datetime as _d
        cutoff = (_d.datetime.now(_d.timezone.utc) - _d.timedelta(days=7)).isoformat()
        n = 0
        seen = set()
        for v in ledger.active_vettings():
            if v.get("approved_by") != reviewer:
                continue
            at = v.get("approved_at") or ""
            if at < cutoff:
                continue
            # Count distinct (iso3, variable) pairs, not per-cell records.
            pair = (v.get("iso3"), v.get("variable"))
            if pair in seen:
                continue
            seen.add(pair)
            n += 1
        return n
    except Exception:
        return 0


def maybe_backup(force: bool = False) -> None:
    """Copy comments.json to backups/comments.YYYYMMDD-HHMMSS.json once per
    invocation when threshold met (here: every 25 saves or every ~5 min)."""
    state = maybe_backup
    if not hasattr(state, "_count"):
        state._count = 0
        state._last = 0.0
    state._count += 1
    import time
    now = time.time()
    if force or state._count % 25 == 0 or (now - state._last) > 300:
        state._last = now
        ts = _dt.datetime.now().strftime("%Y%m%d-%H%M%S")
        try:
            shutil.copyfile(COMMENTS_PATH, BACKUP_DIR / f"comments.{ts}.json")
        except Exception as e:
            print(f"[warn] backup failed: {e}")


def _input_fingerprint(p: Path) -> dict | None:
    """Mirror of flags.py._fingerprint: size + nanosecond mtime, or None if
    absent. Must match flags.py exactly so comparisons are apples-to-apples."""
    try:
        st = p.stat()
    except FileNotFoundError:
        return None
    return {"size": st.st_size, "mtime_ns": st.st_mtime_ns}


# sha256 of flags.py is stable between edits, but manifest_status() is polled
# every 30s per open tab -- cache the hash keyed on the file's mtime so we
# only re-read+hash the ~1000-line source when it actually changes.
_FLAGS_PY_SHA: tuple[int, str] | None = None


def _flags_py_sha() -> str | None:
    global _FLAGS_PY_SHA
    try:
        mtime = FLAGS_PY.stat().st_mtime_ns
    except OSError:
        return None
    if _FLAGS_PY_SHA and _FLAGS_PY_SHA[0] == mtime:
        return _FLAGS_PY_SHA[1]
    sha = hashlib.sha256(FLAGS_PY.read_bytes()).hexdigest()
    _FLAGS_PY_SHA = (mtime, sha)
    return sha


def manifest_status() -> dict:
    """Cheap staleness check for flags.parquet: re-stat the inputs flags.py
    recorded in flags_manifest.json and compare. Stat-only -- no .dta parsing.
    Returns stale + the list of inputs that moved. When no manifest exists yet
    (flags.py never ran with manifest support), staleness is unknown."""
    if not MANIFEST_PATH.exists():
        return {"stale": False, "manifest": False, "changed": [], "generated_at": None}
    try:
        manifest = json.loads(MANIFEST_PATH.read_text() or "{}")
    except Exception as e:
        # A manifest existed but is corrupt/truncated -- we can no longer
        # verify freshness, so prompt a regen rather than claim "up to date".
        return {"stale": True, "manifest": False, "changed": ["(manifest unreadable)"],
                "error": f"manifest unreadable: {e}"}
    changed = []
    for rel, recorded in (manifest.get("inputs") or {}).items():
        if _input_fingerprint(REPO / rel) != recorded:
            changed.append(rel)
    cur_sha = _flags_py_sha()
    if cur_sha is not None and cur_sha != manifest.get("engine_sha256"):
        changed.append("flags.py")
    return {
        "stale": bool(changed),
        "manifest": True,
        "changed": changed,
        "generated_at": manifest.get("generated_at"),
    }


# Job recipes. Each step is (display_name, argv, timeout_seconds).
#   regen      = full recompute: re-read the data, re-run every check, suppress.
#   resuppress = fast path: reload flags.py's cached raw flag set and just
#                re-apply vetting suppression (no .dta reads), then rebuild
#                data.json. Use after approvals when the data hasn't changed.
def _regen_steps() -> list:
    return [("flags.py", [sys.executable, str(FLAGS_PY)], 1800),
            ("build_data.py", [sys.executable, str(BUILD_DATA_PY)], 600)]


def _resuppress_steps() -> list:
    return [("flags.py --resuppress-only", [sys.executable, str(FLAGS_PY), "--resuppress-only"], 300),
            ("build_data.py", [sys.executable, str(BUILD_DATA_PY)], 600)]


def _run_job(steps: list) -> None:
    """Worker thread: run each step in order, updating _REGEN_STATE so
    /regen/status can report progress."""
    def _finish(**kw):
        with _REGEN_LOCK:
            _REGEN_STATE.update(finished_at=_dt.datetime.now().isoformat(timespec="seconds"), **kw)

    tail = ""
    try:
        for name, argv, timeout in steps:
            with _REGEN_LOCK:
                _REGEN_STATE.update(step=name)
            r = subprocess.run(argv, cwd=str(REPO),
                               capture_output=True, text=True, timeout=timeout)
            tail = ((r.stdout or "")[-2000:] + (r.stderr or "")[-2000:]).strip()
            if r.returncode != 0:
                _finish(status="error", error=f"{name} exited {r.returncode}",
                        log_tail=tail, returncode=r.returncode)
                return
        _finish(status="done", error=None, log_tail=tail, returncode=0)
    except subprocess.TimeoutExpired as e:
        _finish(status="error", error=f"{e.cmd} timed out after {e.timeout}s",
                log_tail=tail or None)
    except Exception as e:
        _finish(status="error", error=str(e), log_tail=tail or None)


def start_job(steps: list, kind: str) -> dict:
    """Kick off a background job if none is running. Returns the job state.
    `kind` is 'regen' or 'resuppress' so the dashboard can label it."""
    with _REGEN_LOCK:
        if _REGEN_STATE["status"] == "running":
            return {"started": False, **_REGEN_STATE}
        _REGEN_STATE.update(status="running", kind=kind,
                            started_at=_dt.datetime.now().isoformat(timespec="seconds"),
                            finished_at=None, step=None, error=None, log_tail=None, returncode=None)
        snapshot = dict(_REGEN_STATE)
    threading.Thread(target=_run_job, args=(steps,), daemon=True).start()
    return {"started": True, **snapshot}


class Handler(http.server.SimpleHTTPRequestHandler):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, directory=str(ROOT), **kwargs)

    def log_message(self, fmt: str, *args) -> None:  # quieter logs
        # Always coerce args to str — http.server occasionally passes
        # HTTPStatus enums or ints, which aren't iterable for `in` checks.
        first = str(args[0]) if args else ""
        if "/comment" in fmt or "POST" in first:
            super().log_message(fmt, *args)

    def _send_json(self, status: int, payload: dict, body_bytes: bytes | None = None) -> None:
        self.send_response(status)
        self.send_header("Content-Type", "application/json")
        self.send_header("Cache-Control", "no-store")
        self.end_headers()
        self.wfile.write(body_bytes or json.dumps(payload).encode("utf-8"))

    def _handle_vetting(self, op: str) -> None:
        """POST /vet, /edit, /revoke -- append a vetting record."""
        if ledger is None:
            self._send_json(503, {"error": "ledger unavailable"})
            return
        length = int(self.headers.get("Content-Length", 0))
        body_bytes = self.rfile.read(length) if length else b""
        try:
            payload = json.loads(body_bytes or b"{}")
        except json.JSONDecodeError as e:
            self._send_json(400, {"error": f"bad json: {e}"})
            return
        body = payload.get("body") or payload
        by_user = payload.get("by_user") or body.get("approved_by") or "?"
        try:
            ledger.append(op, body, by_user=by_user)
        except ValueError as e:
            self._send_json(400, {"error": str(e)})
            return
        except Exception as e:
            self._send_json(500, {"error": f"ledger append failed: {e}"})
            return
        # Refresh the markdown so the recoverable record stays current.
        maybe_rebuild_audit_log()
        self._send_json(200, {"ok": True})

    def do_GET(self) -> None:  # noqa: N802
        parsed = urlparse(self.path)
        path = parsed.path
        # /reviewer — current handle + this-week throughput.
        if path == "/reviewer":
            r = get_reviewer()
            self._send_json(200, {"reviewer": r, "reviewed_this_week": reviewed_this_week(r)})
            return
        # /vettings?iso3=ARG&variable=rGDP — return every active vetting
        # for that pair from audit.db. Used by the dashboard to render the
        # "this flag was vetted" panel next to each suppressed flag.
        if path == "/vettings":
            params = parse_qs(parsed.query)
            iso3 = (params.get("iso3") or [""])[0]
            var = (params.get("variable") or [""])[0]
            if ledger is None:
                self._send_json(503, {"error": "ledger unavailable"})
                return
            try:
                active = ledger.active_vettings()
            except Exception as e:
                self._send_json(500, {"error": f"ledger query failed: {e}"})
                return
            if iso3 or var:
                active = [
                    v for v in active
                    if (not iso3 or v["iso3"] == iso3)
                    and (not var or v["variable"] == var)
                ]
            self._send_json(200, {"vettings": active})
            return
        # /history?key=ARG_M2_Mitchell — return every comments.log entry
        # for that key, in chronological order. Lets the dashboard show
        # the full save history of any pair so the user can verify nothing
        # was lost or restore a prior version.
        if path == "/history":
            params = parse_qs(parsed.query)
            keys = params.get("key", [])
            if not keys:
                self._send_json(400, {"error": "missing key parameter"})
                return
            key = keys[0]
            entries = []
            if LOG_PATH.exists():
                for line in LOG_PATH.read_text().splitlines():
                    line = line.strip()
                    if not line:
                        continue
                    try:
                        rec = json.loads(line)
                    except json.JSONDecodeError:
                        continue
                    if rec.get("key") == key:
                        entries.append(rec)
            self._send_json(200, {"key": key, "entries": entries})
            return
        # /regen/status — cheap staleness check (re-stat flags.py's inputs)
        # plus the state of any in-flight regen job. Polled by the dashboard.
        if path == "/regen/status":
            with _REGEN_LOCK:
                job = dict(_REGEN_STATE)
            self._send_json(200, {"job": job, **manifest_status()})
            return
        if path in ("/", "/index.html"):
            if not INDEX_PATH.exists():
                self.send_error(500, "index.html missing")
                return
            self.send_response(200)
            self.send_header("Content-Type", "text/html; charset=utf-8")
            self.send_header("Cache-Control", "no-store")
            self.end_headers()
            self.wfile.write(INDEX_PATH.read_bytes())
            return
        if path == "/data.json":
            if not DATA_PATH.exists():
                self.send_error(500, "data.json missing — run build_data.py first")
                return
            self.send_response(200)
            self.send_header("Content-Type", "application/json")
            self.send_header("Cache-Control", "max-age=3600")
            self.send_header("Content-Length", str(DATA_PATH.stat().st_size))
            self.end_headers()
            with open(DATA_PATH, "rb") as f:
                shutil.copyfileobj(f, self.wfile)
            return
        if path == "/comments.json":
            self.send_response(200)
            self.send_header("Content-Type", "application/json")
            self.send_header("Cache-Control", "no-store")
            self.end_headers()
            self.wfile.write(COMMENTS_PATH.read_bytes())
            return
        # /findings — the reviewer's confirmed errors (open pending-fix items),
        # attributed to a likely source + clustered by root cause, for the
        # "Findings" tab. Rebuilt on demand from the vetting ledger.
        if path == "/findings":
            rebuild_findings()
            if not FINDINGS_PATH.exists():
                self._send_json(200, {"generated": None, "n": 0, "findings": []})
                return
            try:
                data = json.loads(FINDINGS_PATH.read_text() or "{}")
            except Exception as e:
                self._send_json(500, {"error": f"findings read failed: {e}"})
                return
            self._send_json(200, data)
            return
        # Fall through to static serving (e.g. for any other files we ship)
        super().do_GET()

    def do_POST(self) -> None:  # noqa: N802
        # Embed: the git-mutating + heavy-rebuild endpoints are disabled (build/sync
        # happen in the pipeline, not from the browser-facing app).
        if EMBED_MODE and self.path in ("/sync", "/regen", "/resuppress"):
            self._send_json(403, {"error": "disabled in embedded mode"})
            return
        if self.path == "/sync":
            r = commit_and_push_audit_logs()
            self._send_json(200 if r.get("ok") else 500, r)
            return
        # /regen — full recompute of flags.parquet + data.json in the
        # background. /resuppress — fast path: re-apply vetting suppression
        # to the cached raw flags (no data re-read) + rebuild data.json.
        # 202 if started, 409 if a job is already running.
        if self.path == "/regen":
            r = start_job(_regen_steps(), "regen")
            self._send_json(202 if r.get("started") else 409, r)
            return
        if self.path == "/resuppress":
            r = start_job(_resuppress_steps(), "resuppress")
            self._send_json(202 if r.get("started") else 409, r)
            return
        if self.path == "/reviewer":
            length = int(self.headers.get("Content-Length", 0))
            body = self.rfile.read(length) if length else b""
            try:
                handle = json.loads(body or b"{}").get("reviewer", "")
            except json.JSONDecodeError as e:
                self._send_json(400, {"error": f"bad json: {e}"})
                return
            set_reviewer(handle)
            r = get_reviewer()
            self._send_json(200, {"reviewer": r, "reviewed_this_week": reviewed_this_week(r)})
            return
        if self.path in ("/vet", "/revoke", "/edit"):
            self._handle_vetting(self.path[1:])
            return
        if self.path != "/comment":
            self.send_error(404)
            return
        length = int(self.headers.get("Content-Length", 0))
        body = self.rfile.read(length) if length else b""
        try:
            payload = json.loads(body or b"{}")
        except json.JSONDecodeError as e:
            self._send_json(400, {"error": f"bad json: {e}"})
            return
        key = payload.get("key")
        if not isinstance(key, str) or not key:
            self._send_json(400, {"error": "missing key"})
            return

        try:
            comments = json.loads(COMMENTS_PATH.read_text() or "{}")
        except Exception:
            comments = {}

        entry = comments.get(key, {}) or {}
        # Comment text + approved flag are independent: only update what was sent.
        if "comment" in payload:
            entry["comment"] = str(payload.get("comment") or "")
        if "approved" in payload:
            entry["approved"] = bool(payload.get("approved"))
        # Optional explicit disposition. The ledger supports three; the UI
        # used to only reach two (approve->vetted-correct, comment->pending-fix).
        # An explicit status lets the reviewer also record 'known-limitation'
        # (imperfect but won't be fixed). Backward compatible: absent -> inferred.
        if "status" in payload:
            s = str(payload.get("status") or "")
            if s in ("vetted-correct", "known-limitation", "pending-fix"):
                entry["status"] = s
        entry["ts"] = payload.get("ts") or _dt.datetime.now().isoformat(timespec="seconds")
        comments[key] = entry

        # Persist atomically + append-log for safety net.
        atomic_write_text(COMMENTS_PATH, json.dumps(comments, indent=2, sort_keys=True))
        append_log({"key": key, **entry})
        maybe_backup()
        # Fan the comment out into the vetting ledger: one record per
        # currently-flagged cell in this pair. The comments.json entry is
        # the UI cache; the ledger is the authoritative store consulted by
        # flags.py for suppression.
        n_fanout = _fan_out_comment_to_ledger(key, entry)
        # Refresh docs/GMD_AUDIT_LOG.md so the recoverable record stays current.
        maybe_rebuild_audit_log()

        self._send_json(200, {"ok": True, "ts": entry["ts"], "fanout": n_fanout})


def main(argv: list[str]) -> int:
    port = 8765
    if len(argv) > 1:
        # Tolerate stray punctuation/whitespace around the port (e.g. a
        # pasted "8765." with a trailing period) -- strip to digits and
        # fall back to 8765 rather than refusing to launch.
        digits = "".join(ch for ch in argv[1] if ch.isdigit())
        if digits:
            port = int(digits)
        else:
            print(f"ignoring non-numeric port arg {argv[1]!r}; using 8765")

    if not DATA_PATH.exists():
        print("⚠️  data.json not found. Run `python build_data.py` first.")
        # still serve so user can see the error message in browser

    socketserver.ThreadingTCPServer.allow_reuse_address = True
    with socketserver.ThreadingTCPServer(("127.0.0.1", port), Handler) as httpd:
        print(f"Data quality review")
        print(f"  → http://127.0.0.1:{port}/")
        print(f"  comments:  {COMMENTS_PATH}")
        print(f"  log:       {LOG_PATH}")
        print(f"  backups:   {BACKUP_DIR}/")
        print(f"  Ctrl+C to stop.")
        try:
            httpd.serve_forever()
        except KeyboardInterrupt:
            print("\nshutting down — final backup...")
            maybe_backup(force=True)
            if not EMBED_MODE:
                final_commit_and_push()
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
